getgrit/stdlib

- .grit/patterns/js/codecept_to_playwright.md
https://withgrit.slack.com/archives/C06321RC152/p1702474022539109?thread_ts=1702459556.815209&cid=C06321RC152
> feat: preserve codecept tags in description

- .grit/patterns/universal/ai/_ai_transform.md
- .grit/patterns/universal/ai/_js_transform.md
- .grit/patterns/universal/ai/ai.grit
Move all prompt engineering to user space.
> feat: add a GritQL ai_transform function

- .grit/patterns/universal/ai/ai.grit
- .grit/patterns/universal/ai/ai_choose_example.md
All Ai goes through `llm_chat` now.
> fix: remove llm_choice

- .grit/patterns/js/add_playwright_tags.md
- .grit/patterns/js/codecept_to_playwright.md
Also expose the Codecept -> Playwright now it's better developed.
> feat: utility pattern for playwright tags

- .grit/patterns/python/langfuse_v2.md
> feat: migrate `prompt` and `completion`

- .grit/patterns/python/langfuse_v2.md
> feat: convert pydantic enum

- .grit/patterns/js/angularjs_to_angular.md
- .grit/patterns/universal/ai/ai.grit
Mostly just using AI right now.
> POC: convert AngularJS to Angular

- .grit/patterns/js/mux_v8.md
Fix for https://github.com/muxinc/stream.new/pull/190/files#diff-d6c45396523e09d70627ff89d179612a1b6c9c599397e62647c43f2abcaf6a50L39-L41
> fix(mux): del -> delete

- .grit/patterns/js/explicit_type_conversion.md
This PR contain a update to `explicit_type_conversion`
- `Boolean` type conversion
Grit studio link: https://app.grit.io/studio?key=hp_jjK7gPDUlMEXMUSYao
> refactor: refactor/explicit type conversion

- .grit/patterns/js/find-uncaught-http-request.md
This PR contain the Pattern required for https://github.com/getgrit/stdlib/issues/59
Grit studio link: https://app.grit.io/studio?key=QqcKn2oslZDDJPTZGKmmU
Hi @morgante,
I tried to cover all the case, please let me know, if you think something is missing, I will try to add those case also.
> feat: add find uncaught HTTP requests and wrap it with try {} catch{ }

- .grit/patterns/python/openai.md
https://twitter.com/jeffhollan/status/1747472929624138189
> fix(openai): repair a few small things we missed in the migration

- .grit/patterns/js/proto_to_class.md
Used for upgrading https://github.com/davidparsson/junit-report-builder
> feat: javascript prototype class to es6 conversion

- .grit/patterns/js/_no_restricted_imports.md
- .grit/patterns/js/no_restricted.grit
Fills a gap from biome: https://github.com/sourcegraph/cody/pull/2836/files#diff-e2954b558f2aa82baff0e30964490d12942e0e251c1aa56c3294de6ec67b7cf5L64-L76
> feat: add no_restricted_imports pattern

- .grit/patterns/js/react_hooks.grit
- .grit/patterns/js/react_to_hooks.md
Skip adding binding function call form constructor.
> Skip adding bing(this) to constructor statements

- .grit/patterns/js/calling-set-state-on-current-state.md
- .grit/patterns/js/react.grit
Example:
```
const [isOpen, setIsOpen] = useState<boolean>(false);
setIsOpen(isOpen) // does not make sense,
setIsOpen(!isOpen) // should be like this
```
Grit studio link: https://app.grit.io/studio?key=y2I2Yo8VSk2_RxKZLkpkK
> feat: calling setState on the current state is always a no-op. so change the state like $Y(!$X) instead

- .grit/patterns/sql/oracle.grit
removes reliance on autowrap in the oracle pattern
> fix: oracle contains

- .grit/patterns/js/codecept_to_playwright.md
Codecept on a relatively large file previously would not terminate even after an hour, now it terminates in ~25 seconds
> fix: replace multiple nested contains with within

- .grit/patterns/js/migrate_default_imports.md
- .grit/patterns/universal/files.grit
for https://github.com/getgrit/rewriter/issues/8632
> fix: strip extension

- .devcontainer/devcontainer.json
- .github/dependabot.yml
- ops/install.sh
Working off another machine, it's nice if GitHub can pre-initialize everything I need to contribute.
> chore: set up a devcontainer config for easier contributions

- .grit/patterns/js/warning-for-hardcoded-github-token.md
Avoid hard-coding secrets, such as credentials and sensitive data, directly into your application's source code. This practice poses a security risk as the information may be inadvertently leaked.
Grit studio link: https://app.grit.io/studio?key=v4tT4zvRdAozQUk1u4qP5
> feat: warning for hardcoded github token

- .grit/patterns/js/es6_exports.md
- .grit/patterns/js/es6_imports.md
Extended the CJS → ESM import/export patterns
> feat: extend es6 import & export patterns

- .grit/patterns/yaml/concourse_v7.md
> feat: add a across -> in_parallel pattern example

- .grit/patterns/python/open-file-object-never-closed.md
- .grit/patterns/python/py_no_debugger.md
- .grit/patterns/python/remove-debbuger.md
- .grit/patterns/python/warning-for-hardcoded-tmp-path.md
We should remove `debugger` from production code
Grit studio link: https://app.grit.io/studio?key=mqea0iKIQgNu2b-J8KbBA
> feat: remove debugger python

- .grit/patterns/solidity/NestedLoop.md
- old_patterns/shared.grit
remove orelse from the standard library
> chore: no_orelse

- .grit/patterns/go/go_imports.grit
- .grit/patterns/go/path_to_filepath.md
Merge with https://github.com/getgrit/rewriter/pull/9090
> fix: go formatting

- .grit/patterns/yaml/concourse_v7.md
blocked by https://github.com/getgrit/rewriter/pull/9056
> chore: adds another test for concourse

- .grit/patterns/json/public_s3_bucket.md
Detected public S3 bucket. This policy allows anyone to have some kind of access to the bucket. The exact level of access and types of actions allowed will depend on the configuration of bucket policy and ACLs. Please review the bucket configuration to make sure they are set with intended values.
- [AmazonS3](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-control-block-public-access.html)
grit studio link: https://app.grit.io/studio?key=aF_Q_tg-OOU9f6PTX0y9T
> feat: Detected public S3 bucket and make sure they are set with intended values

- .grit/patterns/js/drizzle_mysql_postgresql.md
I have used this migration in the project. Let me know if it is useful here.
> Add Drizzle Schema migration from MySQL to PostgreSQL

- .grit/patterns/go/mux_go_v5.md
Fix some typos and add more methods
> chore: clean up muxgo upgrade guide

- .grit/patterns/js/migrating_from_react_query_3_to_react_query_4.md
react_query pattern was using \`\` to match `$program` instead of using the variable
> fix: react_query 3 to 4

- .grit/patterns/yaml/concourse_v7.md
1. Insert steps
2. Add more test cases
3. Handle `max_in_flight` -> `limit`
> feat: improve concourse pattern

- .grit/patterns/js/es6_imports.md
Handle some edge cases and dynamic imports.
> fix: improve require -> import conversion

- .grit/patterns/js/sonar_autorepair.grit
- .grit/patterns/js/sonar_fix.md
> chore: patterns test

- .grit/patterns/java/unused_private_fields.md
Fixes https://github.com/getgrit/stdlib/issues/207
> fix: look for cross-referenced fields in Java

- .github/workflows/main.yaml
- .grit/patterns/js/marzano.grit
- .grit/patterns/js/no_commented_out_code.md
- .grit/patterns/universal/ai/_ai_is_bare.md
- .grit/patterns/universal/ai/_ai_match.md
- .grit/patterns/universal/ai/_ai_rewrite.md
- .grit/patterns/universal/ai/_ai_transform_simple.md
- .grit/patterns/universal/ai/ai.grit
- .grit/patterns/universal/ai/ai_choose_example.md
- .grit/patterns/universal/ai/ai_rewrite.grit
- .grit/patterns/yaml/marzano.grit
https://github.com/getgrit/stdlib/pull/216 but with more safety
> feat: just the second stage of rewriting

- .grit/patterns/js/marzano.grit
- .grit/patterns/universal/ai/_ai_rewrite.md
- .grit/patterns/universal/ai/_ai_transform_simple.md
- .grit/patterns/universal/ai/ai_rewrite.grit
- .grit/patterns/yaml/marzano.grit
> Revert "feat: restore full ai_rewrite for yaml"

- .github/workflows/dependency-review.yml
- .grit/patterns/java/_java_rewrite_example.md
- .grit/patterns/java/rewrite_simple_functions.md
> feat: enhance Java pattern

- .grit/patterns/python/_test_add_multiple_bare_imports.md
- .grit/patterns/python/_test_ensure_import_from.md
- .grit/patterns/python/_test_python_imports.md
- .grit/patterns/python/math_prod.md
- .grit/patterns/python/py_imports.grit
- .grit/patterns/python/use_flask_jsonify.md
Fixes https://github.com/getgrit/gritql/issues/439
> fix(python) insert new imports after existing imports

- .grit/patterns/python/_test_correct_source.md
- .grit/patterns/python/_test_two_imports.md
- .grit/patterns/python/py_imports.grit
fixes https://github.com/getgrit/gritql/issues/450
fixes https://github.com/getgrit/gritql/issues/449
> fix: repair some bugs with add_import in Python

- .grit/patterns/js/es6_arrow_functions.md
Fixes https://github.com/getgrit/stdlib/issues/238
> fix: handle cases where the arrow function is an object

- .grit/patterns/js/es6_arrow_functions.md
Fixes https://github.com/getgrit/stdlib/issues/243
> fix: repair async functions

- .grit/patterns/js/es6_arrow_functions.md
- .grit/patterns/js/serverless_to_spin.md
- .grit/patterns/json/public_s3_bucket.md
Trying to get stdlib in a place where the Biome parser works on it.
> chore: clean up some patterns for biome compatibility
