.grit/patterns/js/no_commented_out_code.md
=> fix: ignore eslint and other ignore comments when considering no_commented_out_code

.grit/patterns/python/openai.md, .grit/patterns/python/openai_azure.md
https://github.com/openai/openai-python/discussions/742#discussioncomment-8006276
=> fix: replace subscripting in OpenAI responses

.grit/patterns/js/unused_imports.md
In a given `import x, { y, z} from "w'"` import line:
* The pattern now removes only x if x is unused
* It also removes individual named imports like y or z if they are unused
* The pattern also works better with `import type` imports.
=> fix: Update unused_imports pattern to work with `import type`s

.grit/patterns/js/intelligent_useEffect_to_useLayoutEffect.md
This PR contains the initial `POC` for the bellow problem:
https://github.com/getgrit/js/issues/37
Till now, I have figured out that this kind for switch it mostly required when, we are dealing with `ref.current` (If you need to mutate the `DOM` and/or do need to perform measurements)
Grit studio link: https://app.grit.io/studio?key=PvRpvvDRMSQxmDd72DIWE
Hi @morgante, this is open for suggestion, which can help to improve and make it better.
=> feat: add Intelligent useEffect vs useLayoutEffect

.grit/patterns/js/migrating_from_react_query_3_to_react_query_4.md
The pattern will help to migrate from `React Query 3` to `React Query 3`
Reference: https://tanstack.com/query/v4/docs/react/guides/migrating-to-react-query-4
Grit studio link: https://app.grit.io/studio?key=0Xzm-CsbLBPNVTPtNWkwe
=> feat: react query 3 to react query 4 migration

.grit/patterns/js/useless-ternary-operator.md
If `$condition` ? `$answer`:`$answer` then this expression returns $answer. `This is probably a human error`
Grit studio link: https://app.grit.io/studio?key=vdLSOjh9zNgvkekW4_n2a
=> feat: find useless ternary operator

.grit/patterns/js/react_hooks.grit, .grit/patterns/js/react_to_hooks.md
The changes fix the issue from [this PR](https://github.com/preset-io/superset/pull/700/files?diff=split&w=0#r1435420096) where migrations remove the if statement from the React component constructor logs.
=> Keep if statement from React constructor componen

.grit/patterns/js/react_hooks.grit, .grit/patterns/js/react_to_hooks.md
=> Feat/componentDidMount with prevProps

.grit/patterns/js/remove-apollo-graphql-schema-directives-for-v3-v4.md
The `schemaDirectives` option in `Apollo GraphQL`, which was effective in ApolloServer version `v2`, no longer functions in `versions >=3` and above. This change can have significant implications, potentially exposing authenticated endpoints, disabling rate limiting, and more, depending on the directives used. To address this, it is recommended to consult the references on creating custom directives specifically for ApolloServer versions `v3` and `v4`.
- [references](https://www.apollographql.com/docs/apollo-server/schema/directives/#custom-directives)
grit studio link: https://app.grit.io/studio?key=fzZ0QPNvdajWv-cARmnT7
=> feat: remove Use of outdated ApolloServer option 'schemaDirectives'

.grit/patterns/js/graphql-v4-csrf-prevention.md
The Apollo GraphQL server sets the `csrfPrevention` option to `false`. This can enable CSRF attacks.
- [reference](https://www.apollographql.com/docs/apollo-server/v3/security/cors/#preventing-cross-site-request-forgery-csrf)
Grit studio link: https://app.grit.io/studio?key=wyrCHzl5dIrY8Brrw_qiG
=> feat: GraphQL Sever v4 csrf prevention

.grit/patterns/js/move-defined-styled-components-outside-module-level.md, .grit/patterns/js/react.grit, .grit/patterns/js/warning-for-defined-styled-components-on-module-level.md
Creating a styled component inside the render method in React leads to performance issues because it dynamically generates a new component in the DOM on each render. This causes React to discard and recalculate that part of the DOM subtree every time, rather than efficiently updating only the changed parts. This can result in performance bottlenecks and unpredictable behaviour. 
- [reference](https://styled-components.com/docs/faqs#why-should-i-avoid-declaring-styled-components-in-the-render-method)
Grit studio link: https://app.grit.io/studio?key=YjIBFhrAb7ao0Zix-Qaao
Note: Hi @morgante, I was trying to re-write the whole component in correct way, but become very tricky, may be we can have an `issue` open for it for future.
=> feat: move defined styled components outside component module level

.grit/patterns/js/graphql-v3-csrf-prevention.md
The Apollo GraphQL server lacks the `csrfPrevention` option. This option is `false` by the default in v3 of the Apollo GraphQL `v3`, which can enable `CSRF` attacks
Grit studio link: https://app.grit.io/studio?key=zm9i9h90rA1AfLDL-E76C
=> feat: GraphQL Sever v3 csrf prevention

.grit/patterns/js/marzano.grit, .grit/patterns/js/replace-zlib-deflate-to-zlib-deflateSync.md
Creating and using a large number of `zlib` objects simultaneously can cause significant memory fragmentation. It is strongly recommended that the results of compression operations be cached or made synchronous to avoid duplication of effort
- [reference](https://nodejs.org/api/zlib.html#zlib_threadpool_usage_and_performance_considerations)
grit studio link: https://app.grit.io/studio?key=gyYAgSYiiXsJ_ZEsU8S2H
=> feat: replace `zlib.deflate` ⇒ `zlib.deflateSync`

.grit/patterns/js/replaceAll_to_replace.md
Replaces `replaceAll` with `replace`, when have regex pattern.
The `replaceAll` string method may not be supported in all JavaScript versions and older browsers. It is advisable to use the `replace()` method with a regular expression as the first argument. For example, use `mystring.replace(/bad/g, "good") `instead of `mystring.replaceAll("bad", "good")`
- [reference](https://discourse.threejs.org/t/replaceall-is-not-a-function/14585)
grit studio link: https://app.grit.io/studio?key=7VFZdJlsr0u1nn7_X4Ato
=> feat: update replaceAll to replace when have regex pattern

.grit/patterns/python/warning-for-hardcoded-tmp-path.md
Detected hardcoded temp directory. Consider using `tempfile.TemporaryFile` instead
- [reference](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryFile)
grit studio link: https://app.grit.io/studio?key=NH1Hr1ZrIrtO2VBOwtfcB
=> feat: warning for hardcoded tmp path

.grit/patterns/js/replaceAll_to_replace.md, .grit/patterns/python/open-file-object-never-closed.md
We should close the file object opened without corresponding close.
- [reference](https://realpython.com/why-close-file-python/)
grit studio link: https://app.grit.io/studio?key=3x1Ab-H2gVgzopAcZ4YJN
=> feat: close file object opened and never closed

.grit/patterns/python/replace-tempfile-mktemp-with-tempfile-NamedTemporaryFile.md, .grit/patterns/python/replace_tempfile.md
Prefer using `tempfile.NamedTemporaryFile` instead. According to the official Python documentation, the `tempfile.mktemp` function is considered unsafe and should be avoided. This is because the generated file name may initially point to a non-existent file, and by the time you attempt to create it, another process may have already created a file with the same name, leading to potential conflicts.
- [reference](https://docs.python.org/3/library/tempfile.html#tempfile.mkdtemp)
grit studio link: https://app.grit.io/studio?key=FSpX6ou9ZdSg2icZaFO_L
=> feat: replace `tempfile.mktemp` ⇒ `tempfile.NamedTemporaryFile`

.grit/patterns/yaml/concourse_v7.md
fixes bug where concourse upgrade pattern required a trailing newline to match
=> fix: concourse now works with or without trailing newline

.grit/patterns/python/py_no_debugger.md
We should remove debugger from production code
updated it for `as` import also.
ex: `import pdb as db`
grit studio link: https://app.grit.io/studio?key=6FUWscU-mNmbGp3M_WBKg
=> chore: update no debugger pattern

.grit/patterns/go/jwt_go_none_algorithm.md
Using the `none` algorithm in a `JWT` token is risky because it assumes the token's integrity is already ensured. This could let a malicious actor create a fake JWT token that gets automatically verified. Avoid using `none` and go for a safer algorithm like `HS256` instead.
- [Cryptographic_Failures](https://owasp.org/Top10/A02_2021-Cryptographic_Failures)
grit studio link: https://app.grit.io/studio?key=06k24S6dFct2mmhlQrRO_
=> feat: replace `jwt.SigningMethodNone` ⇒ `jwt.SigningMethodHS256`

.grit/patterns/go/useless_if_else_body.md
Identical statements found in both the `if` and `else` bodies of an `if-statement`. This results in the same code execution regardless of the if-expression outcome. To optimize, eliminate the `if` statement entirely.
grit studio link: https://app.grit.io/studio?key=EyccL37fsQzbsuzKLQEdD
=> feat: useless if conditional

.grit/patterns/go/go_imports.grit, .grit/patterns/go/path_to_filepath.md
Utilize `filepath.Join(...)` instead of `path.Join(...)` as it accommodates OS-specific path separators, mitigating potential issues on systems like Windows that may employ different delimiters.
- [path.join-considered-harmful](https://parsiya.net/blog/2019-03-09-path.join-considered-harmful/)
- [path.go](https://go.dev/src/path/path.go?s=4034:4066#L145)
grit studio link: https://app.grit.io/studio?key=EcRvmSnLb7iBt1z5mzboh
=> feat: replace `path.Join()` ⇒ `filepath.Join()`

.grit/patterns/go/no_unnecessary_conditionals.md, .grit/patterns/go/warning_bad_comparison.md
Identified redundant if statement: `if (True)`, `if (False)`  consistently yield the same outcome, making one of the expressions unnecessary in the code. Remove either the `if (False)` segment entirely or the `if (True)` comparison, depending on which is present in the code.
grit studio link: https://app.grit.io/studio?key=lgKcxKqerGulQp-9rAZQo
=> feat: Avoid unnecessary if statements

.grit/patterns/json/wildcard_assume_role.md
Detected wildcard access granted to sts:AssumeRole. This means anyone with your AWS account ID and the name of the role can assume the role. Instead, limit to a specific identity in your account, like this: `arn:aws:iam::<account_id>:root`.
- [aws](https://rhinosecuritylabs.com/aws/assume-worst-aws-assume-role-enumeration/)
grit studio link: https://app.grit.io/studio?key=FYBOCusMydFhnaYVM89eP
=> feat: Detected wildcard access granted to sts:AssumeRole and limit to a specific identity in your account

.grit/patterns/js/_convert_default_exports.md, .grit/patterns/js/add_type_caught_errors.md, .grit/patterns/js/chai_to_jest.md, .grit/patterns/js/drizzle_mysql_postgresql.md, .grit/patterns/js/enforce_strict_equality_check.md
The extra commas have broken parsing for all affected files, making titles stop working.
=> fix: frontmatter commas

.grit/patterns/js/add_try_catch_async_functions.md
removes unnecessary flavor declaration from add_try_catch_async pattern
=> chore: only one flavor

.grit/patterns/python/no_null_string_field.md
Avoid using null on string-based fields such as `CharField` and `TextField`. If a string-based field has `null=True`, that means it has two possible values for `no data`: `NULL`, and the empty string. In most cases, it's redundant to have two possible values for "no data" the Django convention is to use the empty string, not `NULL`.
grit studio link: https://app.grit.io/studio?key=1WUuiSif_4CSNMfUHd4I7
=> feat: Avoid using `null` on string-based fields such as CharField and TextField

.grit/patterns/python/json-response-vs-json.md
`JsonResponse` in Django offers a concise and efficient way to return `JSON` responses compared to using `json.dumps` along with `HttpResponse`. It simplifies the process by automatically handling serialization and setting the correct content type.
grit studio link: https://app.grit.io/studio?key=VRDugRVXYb4RxWOy5TJJj
=> feat: use `JsonResponse` over `json` and `HttpResponse`

.grit/patterns/rust/use_secure_hashes.md
The hashing functions `md2`, `md4`, `md5`, and `sha1` are detected as cryptographically insecure due to known vulnerabilities. It is advisable to use more secure hashing algorithms for cryptographic purposes.
references:
- [RustCrypto](https://github.com/RustCrypto/hashes)
- [md2](https://docs.rs/md2/latest/md2/)
- [md4](https://docs.rs/md4/latest/md4/)
- [md5](https://docs.rs/md5/latest/md5/)
- [sha1](https://docs.rs/sha-1/latest/sha1/)
grit studio link: https://app.grit.io/studio?key=ubJSaHYfHLppILL8SyFj7
=> feat: Use secure hashes

.grit/patterns/python/use_flask_jsonify.md
`flask.jsonify()` is a `Flask` helper method which handles the correct settings for returning `JSON` from `Flask` routes
- [flask.json.jsonify](https://flask.palletsprojects.com/en/2.2.x/api/#flask.json.jsonify)
grit studio link: https://app.grit.io/studio?key=LvkuxTqgej4s9njaENm5g
=> feat: use `flask.jsonify()`

.grit/patterns/python/warning-for-hardcoded-tmp-path.md
we would like to require empty fields in snippets to match by default. This change allows warning-for-hardcoded-tmp-path to match using this criteria
=> fix: add missing variable for warning-for-hardcoded-tmp-path

.grit/patterns/python/tempfile-without-flush.md
we would like to require empty fields in snippets to match by default. This change allows tempfile-without-flush to match using this criteria
=> fix: add missing metavariable in temfile-without-flush

.grit/patterns/js/moment-to-date-fns.grit
we would like to require empty fields in snippets to match by default. This change allows moment_to_date to match using this criteria
=> fix: add missing variable in moment_to_date

.grit/patterns/python/open_file_object_never_closed.md
we would like to require empty fields in snippets to match by default. This change allows open_file_object_never_closed to match using this criteria
=> fix: add missing metavariable to open_file_object_never_closed

.grit/patterns/python/py_no_debugger.md
we would like to require empty fields in snippets to match by default. This change allows py_no_debugger to match using this criteria
=> fix: add missing metavariable to py_no_debugger

.grit/patterns/python/collection_to_bool.md
we would like to require empty fields in snippets to match by default. This change allows collection_to_bool to match using this criteria
=> fix: add missing metavariable to collection_to_bool

.grit/patterns/rust/cargo_use_long_dependency.md
I often prefer to switch to this syntax since it makes everything uniform and makes versions easy to toggle.
=> feat: add a simple Cargo.toml transform

.grit/patterns/java/correct_true_comparison_operator.md
Assignment inside a condition is usually accidental, this is likely meant to be a comparison.
=> feat:  correct true comparison `($x = true)`

.grit/patterns/java/correct_false_comparison_operator.md.md
Assignment inside a condition like this `$x = false` is usually accidental, this is likely meant to be a `$x`
=> feat: Correct comparison operator `$x = false`

.grit/patterns/css/aspect_ratio.md, .grit/patterns/go/channel_guarded_with_mutex.md, .grit/patterns/go/exported_loop_pointer.md, .grit/patterns/go/hidden_goroutine.md, .grit/patterns/go/useless_if_else_body.md, .grit/patterns/java/unnecessary_equality_comparison.md, .grit/patterns/js/_no_restricted_imports.md, .grit/patterns/js/find_uncaught_http_request.md, .grit/patterns/js/importing.md, .grit/patterns/js/mui4_to_mui5.md, .grit/patterns/js/no_dead_code.md, .grit/patterns/js/no_inline_if.md, .grit/patterns/python/cleaned_data_vs_post.md, .grit/patterns/python/insecure_hash_function.md, .grit/patterns/python/json_response_vs_json.md, .grit/patterns/python/no_null_string_field.md, .grit/patterns/python/re_match_walrus.md, .grit/patterns/python/tempfile_without_flush.md, .grit/patterns/python/use_defusedcsv.md, .grit/patterns/python/use_flask_jsonify.md, .grit/patterns/rust/cargo_use_long_dependency.md, .grit/patterns/rust/no_useless_format.md, .grit/patterns/rust/use_secure_hashes.md, .grit/patterns/solidity/EtherTransfer.md, .grit/patterns/solidity/NestedLoop.md, .grit/patterns/solidity/NoMulDivRoundUp.md, .grit/patterns/solidity/NoUnusedVariables.md
prep for https://github.com/getgrit/gritql/pull/161
=> chore: differentiate no result and match

.grit/patterns/python/airflow_decorator_syntax.md, .grit/patterns/terraform/kv_pair.md
=> fix: airflow and kv pair

.grit/patterns/python/re_match_walrus.md
re_match_walrus relies on join not distributing indents, this removes this assumption
=> fix: re_match_walrus pads incorrectly

.grit/patterns/python/py_todo.grit
building up a string causes smart insert to add too many newlines, using a list and join instead fixes this.
=> fix: use a list for todo so that padding fix doesn't break openai

.grit/patterns/js/curly.md, .grit/patterns/js/replaceAll_to_replace.md, .grit/patterns/js/useless_ternary_operator.md
Just getting my feet wet learning `gritql` and going through the example JS/TS patterns, I noticed some minor typos.
Following the contributing guidelines, I ran `grit patterns test` locally and got `198 out of 611 samples failed` which seems unrelated to this PR.
=> Fix minor typos in patterns

.grit/patterns/js/react_named_imports.md
This pattern replaces React default import method references (e.g. `React.ReactNode`) with _destructured named imports_ (`import { ReactNode } from 'react'`).
Running this will also make sure that `React` is imported.
_This is mainly a pattern is used on my current code base, but I hope it can be useful to others._
Using the _destructured named imports_ is the recommended way to use React imports.
When this pattern is used in combination with a linter/ formatter (e.g. `Biome`) you can easily optimize legacy React code bases.
This pattern always adds a new import when there is non-destructured import (if your coding style requires it) e.g.
```ts
// this:
import React from 'react';
import { ReactNode } from 'react';
// instead of this:
import React, { ReactNode } from 'react';
``` …
=> feat: implement pattern to replace `React` default import method references with destuctured named imports

.grit/patterns/python/_test_conditional_imports.md, .grit/patterns/python/py_imports.grit
Find the last statement in the "import block" and add imports after that.
Fixes https://github.com/getgrit/gritql/issues/524
=> fix: make the Python importing algorithm smarter
